name: Build Matrix

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build for (comma-separated)'
        required: false
        default: 'ubuntu-latest,windows-latest,macos-latest'
      python_versions:
        description: 'Python versions to build for (comma-separated)'
        required: false
        default: '3.11,3.12,3.13'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']
        exclude:
          # Focus on Python 3.12 for cross-platform testing
          - os: windows-latest
            python-version: '3.11'
          - os: macos-latest
            python-version: '3.11'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.9.1

    - name: Install dependencies
      run: pixi install

    - name: Run tests
      run: pixi run check

    - name: Build executable
      run: pixi run build-exe

    - name: Test executable
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ./dist/iiif-downloader.exe --help
        else
          ./dist/iiif-downloader --help
        fi
        echo "Executable test passed"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: iiif-downloader-${{ matrix.os }}-py${{ matrix.python-version }}-${{ github.sha }}
        path: dist/
        retention-days: 30
